string node
int32 GainP
int32 GainI
int32 GainD
int32 GainFF
int32 GainBEMF
int32 Mode # internal used for hacking 1 = use filtered error signal 
string ControlMode # torque, position, pwm, current etc.
int32 Alpha # 0 -> 100 to change overall stiffness
int32 GravityCompensationTorque
--- 
bool result